apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: ml-pipeline
spec:
  selector:
    app: modelinference
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
